Repository Zalk0/ChouetteBot-discord, pull requests merged in 2024-03, with the labels that each got.

#8 Fix errors
  bot.py
  commands/misc.py
Labels: bug, enhancement

#9 Bot updates and speedup
  .dockerignore
  .github/workflows/ruff.yaml
  Dockerfile
  bot.py
  commands_list.py
  docker-compose.yaml.example
  requirements.txt
  utils/latex_render.py
Labels: enhancement

#10 Docker modifications
  .github/workflows/docker-image.yml
  README.md
Labels: enhancement

#11 feat: try to add rust to build python packages
  .github/workflows/docker-image.yml
  Dockerfile
Labels: bug

#16 Merge clean changes of docker build
  .github/workflows/docker-image.yml
  Dockerfile
  README.md
  commands/misc.py
  docker-compose.yaml.example
  utils/skyblock_guild.py
Labels: enhancement
