Repository Zalk0/ChouetteBot-discord, pull requests merged in 2024-04, with the labels that each got.

#17 feat: add bot info command and improve dev experience
  .github/dependabot.yaml
  .github/workflows/docker-image.yaml
  .github/workflows/docker-image.yml
  .github/workflows/ruff.yaml
  .pre-commit-config.yaml
  Dockerfile
  README.md
  bot.py
  commands/misc.py
  commands_list.py
  docker-compose.yaml.example
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  utils/github_api.py
  utils/latex_render.py
  utils/skyblock_guild.py
Labels: enhancement

#20 fix: readme and bump dev deps
  .github/dependabot.yaml
  .pre-commit-config.yaml
  README.md
  requirements-dev.txt
Labels: documentation, dependencies

#25 Feat: improve birthday list output and change strings to french
  Dockerfile
  README.md
  commands/birthdays.py
  tasks.py
  utils/birthdays.py
Labels: enhancement

#29 Add bot version info in logs
  .github/workflows/docker-image.yaml
  Dockerfile
  README.md
  bot.py
  commands/birthdays.py
  docker-compose.yaml.example
  utils/birthdays.py
  utils/github_api.py
  utils/skyblock_guild.py
  utils/version.py
Labels: enhancement

#30 Add version info in logs + change pre-commit.ci target branch
  .github/workflows/docker-image.yaml
  .pre-commit-config.yaml
  Dockerfile
  README.md
  bot.py
  commands/birthdays.py
  docker-compose.yaml.example
  utils/birthdays.py
  utils/github_api.py
  utils/skyblock_guild.py
  utils/version.py
Labels: documentation, enhancement
